#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 29 15:18:30 2024

@author: vpremier
"""

import openeo


eoconn = openeo.connect('https://openeo.dataspace.copernicus.eu/', auto_validate=False)
eoconn.authenticate_oidc()

eoconn.describe_account()


s2_bands = eoconn.load_collection(
    "SENTINEL2_L2A",
    spatial_extent={'west':10.65,
                    'east':11.1,
                    'south':46.55,
                    'north':46.8,
                    'crs':4326},
    bands=['B03','B11'],
    temporal_extent=['2023-08-02', '2023-08-15'],
)

scl = eoconn.load_collection(
    "SENTINEL2_L2A",
    spatial_extent={'west':10.65,
                    'east':11.1,
                    'south':46.55,
                    'north':46.8,
                    'crs':4326},
    bands=['SCL'],
    temporal_extent=['2023-08-02', '2023-08-15'],
)


s2_cal = s2_bands.apply(lambda x: 0.0001 * x)  

cloud_mask = calculate_cloud_mask(scl)

s2_masked = s2_bands.mask(cloud_mask_tmp)
ndsi = calculate_ndsi(s2_masked)
scf = salomonson(ndsi)